services:
  - type: web
    name: sos-maternidade
    env: node
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: /data/db.json
